// Comprehensive job roles library - pure job titles only
// Organized by category for better maintainability

const techRoles = [
  // Frontend
  "Frontend Developer",
  "Frontend Engineer",
  "Senior Frontend Developer",
  "Senior Frontend Engineer",
  "Lead Frontend Developer",
  "Principal Frontend Engineer",
  "Staff Frontend Engineer",
  "React Developer",
  "React Engineer",
  "Senior React Developer",
  "Senior React Engineer",
  "React Native Developer",
  "Vue.js Developer",
  "Senior Vue.js Developer",
  "Angular Developer",
  "Senior Angular Developer",
  "JavaScript Developer",
  "Senior JavaScript Developer",
  "TypeScript Developer",
  "Senior TypeScript Developer",
  "Next.js Developer",
  "UI Developer",
  "UI Engineer",
  "Web Developer",
  "Senior Web Developer",
  "Frontend Architect",
  
  // Backend
  "Backend Developer",
  "Backend Engineer",
  "Senior Backend Developer",
  "Senior Backend Engineer",
  "Lead Backend Developer",
  "Principal Backend Engineer",
  "Staff Backend Engineer",
  "Node.js Developer",
  "Senior Node.js Developer",
  "Python Developer",
  "Senior Python Developer",
  "Python Engineer",
  "Java Developer",
  "Senior Java Developer",
  "Java Engineer",
  "Go Developer",
  "Golang Developer",
  "Senior Go Developer",
  "Ruby Developer",
  "Ruby on Rails Developer",
  "Senior Ruby Developer",
  "PHP Developer",
  "Senior PHP Developer",
  "C# Developer",
  ".NET Developer",
  "Senior .NET Developer",
  "Scala Developer",
  "Rust Developer",
  "Senior Rust Developer",
  "Django Developer",
  "Spring Boot Developer",
  "FastAPI Developer",
  "API Developer",
  "API Engineer",
  "Backend Architect",
  
  // Full Stack
  "Full Stack Developer",
  "Full Stack Engineer",
  "Senior Full Stack Developer",
  "Senior Full Stack Engineer",
  "Lead Full Stack Developer",
  "MERN Stack Developer",
  "MEAN Stack Developer",
  "JAMstack Developer",
  "Full Stack Architect",
  
  // Mobile
  "Mobile Developer",
  "Mobile Engineer",
  "Senior Mobile Developer",
  "Senior Mobile Engineer",
  "iOS Developer",
  "Senior iOS Developer",
  "iOS Engineer",
  "Android Developer",
  "Senior Android Developer",
  "Android Engineer",
  "Swift Developer",
  "Kotlin Developer",
  "Flutter Developer",
  "Senior Flutter Developer",
  "Cross-Platform Mobile Developer",
  "Mobile Architect",
  
  // Software Engineering (General)
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Software Engineer",
  "Principal Software Engineer",
  "Distinguished Engineer",
  "Software Developer",
  "Senior Software Developer",
  "Software Architect",
  "Solutions Architect",
  "Technical Architect",
  "Enterprise Architect",
  "Systems Architect",
  
  // Data
  "Data Engineer",
  "Senior Data Engineer",
  "Lead Data Engineer",
  "Principal Data Engineer",
  "Data Analyst",
  "Senior Data Analyst",
  "Business Intelligence Analyst",
  "BI Developer",
  "Analytics Engineer",
  "Senior Analytics Engineer",
  "Big Data Engineer",
  "ETL Developer",
  "Data Warehouse Engineer",
  "Database Administrator",
  "Senior Database Administrator",
  "Database Engineer",
  
  // Machine Learning & AI
  "Machine Learning Engineer",
  "Senior Machine Learning Engineer",
  "ML Engineer",
  "Senior ML Engineer",
  "AI Engineer",
  "Senior AI Engineer",
  "Data Scientist",
  "Senior Data Scientist",
  "Lead Data Scientist",
  "Principal Data Scientist",
  "Research Scientist",
  "AI Research Scientist",
  "Applied Scientist",
  "MLOps Engineer",
  "Computer Vision Engineer",
  "NLP Engineer",
  "Deep Learning Engineer",
  "AI/ML Researcher",
  
  // DevOps & Infrastructure
  "DevOps Engineer",
  "Senior DevOps Engineer",
  "Lead DevOps Engineer",
  "Site Reliability Engineer",
  "Senior SRE",
  "SRE Manager",
  "Cloud Engineer",
  "Senior Cloud Engineer",
  "Cloud Architect",
  "AWS Engineer",
  "Azure Engineer",
  "GCP Engineer",
  "Infrastructure Engineer",
  "Senior Infrastructure Engineer",
  "Platform Engineer",
  "Senior Platform Engineer",
  "Kubernetes Engineer",
  "Systems Engineer",
  "Senior Systems Engineer",
  "Systems Administrator",
  "Linux Administrator",
  "Network Engineer",
  "Network Administrator",
  "Release Engineer",
  "Build Engineer",
  
  // Security
  "Security Engineer",
  "Senior Security Engineer",
  "Application Security Engineer",
  "Cloud Security Engineer",
  "Cybersecurity Engineer",
  "Security Architect",
  "Penetration Tester",
  "Security Analyst",
  "Security Operations Engineer",
  "Cryptography Engineer",
  "Information Security Analyst",
  "Security Consultant",
  
  // QA & Testing
  "QA Engineer",
  "Senior QA Engineer",
  "Quality Assurance Engineer",
  "Test Automation Engineer",
  "Senior Test Automation Engineer",
  "SDET",
  "Senior SDET",
  "QA Lead",
  "QA Manager",
  "Performance Test Engineer",
  "Quality Assurance Analyst",
  "Manual Tester",
  
  // Specialized Tech
  "Blockchain Developer",
  "Senior Blockchain Developer",
  "Smart Contract Developer",
  "Web3 Developer",
  "Game Developer",
  "Senior Game Developer",
  "Game Programmer",
  "Unity Developer",
  "Unreal Developer",
  "Embedded Systems Engineer",
  "Firmware Engineer",
  "Embedded Software Engineer",
  "Graphics Engineer",
  "3D Graphics Programmer",
  "Audio Engineer",
  "Video Engineer",
  "Streaming Engineer",
  "Compiler Engineer",
  "Systems Programmer",
  "Low-Level Developer",
  "Kernel Developer",
  "Robotics Engineer",
  "AR/VR Developer",
  "XR Developer",
  "WebGL Developer",
  "Quantum Computing Engineer",
  
  // Tech Leadership
  "Tech Lead",
  "Technical Lead",
  "Engineering Lead",
  "Team Lead",
  "Engineering Manager",
  "Senior Engineering Manager",
  "Director of Engineering",
  "VP of Engineering",
  "Head of Engineering",
  "CTO",
  "Chief Technology Officer",
  "VP of Technology",
  "Technical Director",
]

const productRoles = [
  "Product Manager",
  "Senior Product Manager",
  "Lead Product Manager",
  "Principal Product Manager",
  "Group Product Manager",
  "Director of Product",
  "VP of Product",
  "Head of Product",
  "Chief Product Officer",
  "CPO",
  "Associate Product Manager",
  "Junior Product Manager",
  "Technical Product Manager",
  "Senior Technical Product Manager",
  "Product Owner",
  "Senior Product Owner",
  "Product Analyst",
  "Product Operations Manager",
  "Product Strategist",
  "Growth Product Manager",
  "Platform Product Manager",
  "Technical Program Manager",
  "Senior Technical Program Manager",
  "Program Manager",
  "Senior Program Manager",
  "Project Manager",
  "Senior Project Manager",
  "IT Project Manager",
  "Scrum Master",
  "Agile Coach",
  "Delivery Manager",
  "Release Manager",
]

const designRoles = [
  // Product & UX Design
  "Product Designer",
  "Senior Product Designer",
  "Lead Product Designer",
  "Principal Product Designer",
  "Staff Product Designer",
  "UX Designer",
  "Senior UX Designer",
  "Lead UX Designer",
  "UX Architect",
  "UI Designer",
  "Senior UI Designer",
  "UI/UX Designer",
  "Senior UI/UX Designer",
  "Visual Designer",
  "Senior Visual Designer",
  "Interaction Designer",
  "Senior Interaction Designer",
  "Experience Designer",
  "Service Designer",
  "Design Systems Designer",
  "Motion Designer",
  "Senior Motion Designer",
  
  // Research
  "UX Researcher",
  "Senior UX Researcher",
  "Lead UX Researcher",
  "User Researcher",
  "Design Researcher",
  
  // Design Leadership
  "Design Lead",
  "Design Manager",
  "Senior Design Manager",
  "Head of Design",
  "Director of Design",
  "VP of Design",
  "Chief Design Officer",
  "Creative Director",
  "Executive Creative Director",
  "Art Director",
  "Senior Art Director",
  
  // Other Design
  "Graphic Designer",
  "Senior Graphic Designer",
  "Brand Designer",
  "Senior Brand Designer",
  "Web Designer",
  "Senior Web Designer",
  "Content Designer",
  "UX Writer",
  "Senior UX Writer",
  "Illustrator",
  "Digital Designer",
  "Marketing Designer",
  "Print Designer",
  "Package Designer",
  "Environmental Designer",
  "Interior Designer",
  "Fashion Designer",
  "Industrial Designer",
  "3D Designer",
  "Animation Designer",
  "Photographer",
  "Videographer",
]

const salesRoles = [
  "Sales Representative",
  "Sales Associate",
  "Sales Executive",
  "Account Executive",
  "Senior Account Executive",
  "Enterprise Account Executive",
  "Strategic Account Executive",
  "Sales Development Representative",
  "SDR",
  "Business Development Representative",
  "BDR",
  "Inside Sales Representative",
  "Outside Sales Representative",
  "Field Sales Representative",
  "Sales Manager",
  "Senior Sales Manager",
  "Regional Sales Manager",
  "Territory Sales Manager",
  "District Sales Manager",
  "National Sales Manager",
  "Sales Director",
  "VP of Sales",
  "Head of Sales",
  "Chief Revenue Officer",
  "CRO",
  "Account Manager",
  "Senior Account Manager",
  "Key Account Manager",
  "Strategic Account Manager",
  "Customer Success Manager",
  "Senior Customer Success Manager",
  "Customer Success Director",
  "VP of Customer Success",
  "Sales Engineer",
  "Solutions Engineer",
  "Pre-Sales Engineer",
  "Sales Consultant",
  "Sales Operations Manager",
  "Sales Enablement Manager",
  "Channel Sales Manager",
  "Partner Manager",
  "Alliance Manager",
  "Revenue Operations Manager",
  "Business Development Manager",
  "Senior Business Development Manager",
  "Director of Business Development",
]

const marketingRoles = [
  "Marketing Manager",
  "Senior Marketing Manager",
  "Marketing Director",
  "VP of Marketing",
  "Head of Marketing",
  "Chief Marketing Officer",
  "CMO",
  "Marketing Coordinator",
  "Marketing Associate",
  "Marketing Specialist",
  "Digital Marketing Manager",
  "Senior Digital Marketing Manager",
  "Digital Marketing Specialist",
  "Performance Marketing Manager",
  "Senior Performance Marketing Manager",
  "Growth Marketing Manager",
  "Head of Growth",
  "VP of Growth",
  "Growth Manager",
  "Content Marketing Manager",
  "Senior Content Marketing Manager",
  "Content Strategist",
  "Content Director",
  "Content Writer",
  "Senior Content Writer",
  "Copywriter",
  "Senior Copywriter",
  "Social Media Manager",
  "Senior Social Media Manager",
  "Social Media Strategist",
  "Community Manager",
  "SEO Manager",
  "Senior SEO Manager",
  "SEO Specialist",
  "SEM Specialist",
  "PPC Specialist",
  "Paid Media Manager",
  "Brand Manager",
  "Senior Brand Manager",
  "Brand Strategist",
  "Email Marketing Manager",
  "Email Marketing Specialist",
  "CRM Manager",
  "Product Marketing Manager",
  "Senior Product Marketing Manager",
  "Director of Product Marketing",
  "Partner Marketing Manager",
  "Field Marketing Manager",
  "Event Marketing Manager",
  "Demand Generation Manager",
  "Lead Generation Manager",
  "Marketing Analyst",
  "Marketing Operations Manager",
  "Influencer Marketing Manager",
  "Affiliate Marketing Manager",
  "Marketing Automation Specialist",
  "Marketing Communications Manager",
  "Public Relations Manager",
  "PR Specialist",
  "Communications Manager",
  "Communications Director",
  "Corporate Communications Manager",
  "Investor Relations Manager",
  "Internal Communications Manager",
]

const financeRoles = [
  "Financial Analyst",
  "Senior Financial Analyst",
  "Finance Manager",
  "Senior Finance Manager",
  "Finance Director",
  "VP of Finance",
  "Chief Financial Officer",
  "CFO",
  "Controller",
  "Financial Controller",
  "Assistant Controller",
  "Accountant",
  "Senior Accountant",
  "Staff Accountant",
  "Accounting Manager",
  "Tax Accountant",
  "Tax Manager",
  "Auditor",
  "Senior Auditor",
  "Internal Auditor",
  "External Auditor",
  "Accounts Payable Specialist",
  "Accounts Receivable Specialist",
  "Accounts Payable Manager",
  "Bookkeeper",
  "Payroll Specialist",
  "Payroll Manager",
  "Treasury Analyst",
  "Treasury Manager",
  "FP&A Analyst",
  "FP&A Manager",
  "Budget Analyst",
  "Investment Analyst",
  "Portfolio Manager",
  "Investment Manager",
  "Wealth Manager",
  "Financial Advisor",
  "Financial Planner",
  "Risk Analyst",
  "Credit Analyst",
  "Loan Officer",
  "Underwriter",
  "Actuary",
  "Quantitative Analyst",
  "Quant Developer",
  "Trader",
  "Investment Banker",
  "Private Equity Associate",
  "Venture Capital Associate",
]

const hrRoles = [
  "HR Coordinator",
  "HR Specialist",
  "HR Generalist",
  "Senior HR Generalist",
  "HR Manager",
  "Senior HR Manager",
  "HR Director",
  "VP of HR",
  "VP of People",
  "Head of People",
  "Chief People Officer",
  "Chief Human Resources Officer",
  "CHRO",
  "HR Business Partner",
  "Senior HR Business Partner",
  "Recruiter",
  "Senior Recruiter",
  "Technical Recruiter",
  "Senior Technical Recruiter",
  "Recruiting Manager",
  "Talent Acquisition Manager",
  "Talent Acquisition Director",
  "Head of Talent",
  "Sourcer",
  "Recruitment Coordinator",
  "People Operations Manager",
  "People Operations Specialist",
  "Compensation Analyst",
  "Compensation Manager",
  "Benefits Manager",
  "Compensation and Benefits Manager",
  "Total Rewards Manager",
  "Employee Relations Manager",
  "Employee Relations Specialist",
  "Diversity and Inclusion Manager",
  "D&I Manager",
  "DEI Manager",
  "Learning and Development Manager",
  "L&D Manager",
  "Training Manager",
  "Corporate Trainer",
  "Organizational Development Manager",
  "HRIS Analyst",
  "HRIS Manager",
  "HR Analyst",
  "Workforce Planning Manager",
]

const operationsRoles = [
  "Operations Manager",
  "Senior Operations Manager",
  "Operations Director",
  "VP of Operations",
  "Head of Operations",
  "Chief Operating Officer",
  "COO",
  "Operations Analyst",
  "Operations Coordinator",
  "Operations Associate",
  "Business Operations Manager",
  "Business Operations Analyst",
  "Strategy and Operations Manager",
  "Revenue Operations Manager",
  "RevOps Manager",
  "Supply Chain Manager",
  "Senior Supply Chain Manager",
  "Supply Chain Analyst",
  "Supply Chain Director",
  "Logistics Manager",
  "Logistics Coordinator",
  "Logistics Analyst",
  "Warehouse Manager",
  "Warehouse Supervisor",
  "Distribution Manager",
  "Inventory Manager",
  "Inventory Analyst",
  "Procurement Manager",
  "Procurement Specialist",
  "Purchasing Manager",
  "Buyer",
  "Senior Buyer",
  "Category Manager",
  "Vendor Manager",
  "Supplier Manager",
  "Fulfillment Manager",
  "Production Manager",
  "Production Supervisor",
  "Manufacturing Manager",
  "Plant Manager",
  "Process Improvement Manager",
  "Continuous Improvement Manager",
  "Lean Manager",
  "Six Sigma Black Belt",
  "Quality Manager",
  "Quality Assurance Manager",
  "Quality Control Manager",
  "Facilities Manager",
  "Office Manager",
]

const customerServiceRoles = [
  "Customer Service Representative",
  "Customer Support Representative",
  "Customer Service Specialist",
  "Customer Support Specialist",
  "Customer Service Agent",
  "Support Agent",
  "Customer Service Manager",
  "Customer Support Manager",
  "Customer Experience Manager",
  "Customer Experience Director",
  "Head of Customer Experience",
  "Call Center Representative",
  "Call Center Manager",
  "Call Center Director",
  "Technical Support Specialist",
  "Technical Support Engineer",
  "IT Support Specialist",
  "Help Desk Specialist",
  "Help Desk Manager",
  "Support Team Lead",
  "Client Services Manager",
  "Client Success Manager",
  "Client Relations Manager",
  "Customer Advocate",
  "Customer Care Specialist",
]

const legalRoles = [
  "Attorney",
  "Senior Attorney",
  "Associate Attorney",
  "Partner",
  "Senior Partner",
  "Managing Partner",
  "Lawyer",
  "Corporate Lawyer",
  "Corporate Counsel",
  "Senior Corporate Counsel",
  "In-House Counsel",
  "General Counsel",
  "Chief Legal Officer",
  "CLO",
  "Legal Counsel",
  "Senior Legal Counsel",
  "Intellectual Property Attorney",
  "Patent Attorney",
  "Employment Attorney",
  "Contract Attorney",
  "Litigation Attorney",
  "Trial Lawyer",
  "Tax Attorney",
  "Real Estate Attorney",
  "Immigration Attorney",
  "Criminal Defense Attorney",
  "Family Law Attorney",
  "Paralegal",
  "Senior Paralegal",
  "Legal Assistant",
  "Legal Secretary",
  "Legal Analyst",
  "Legal Operations Manager",
  "Contract Manager",
  "Contracts Administrator",
  "Compliance Officer",
  "Senior Compliance Officer",
  "Compliance Manager",
  "Compliance Director",
  "Chief Compliance Officer",
  "Regulatory Affairs Manager",
  "Regulatory Specialist",
]

const healthcareRoles = [
  "Registered Nurse",
  "RN",
  "Licensed Practical Nurse",
  "LPN",
  "Nurse Practitioner",
  "Clinical Nurse",
  "Charge Nurse",
  "Nurse Manager",
  "Director of Nursing",
  "Physician",
  "Doctor",
  "Medical Doctor",
  "MD",
  "Surgeon",
  "Specialist Physician",
  "Physician Assistant",
  "PA",
  "Medical Assistant",
  "Clinical Research Coordinator",
  "Clinical Research Associate",
  "Clinical Trial Manager",
  "Healthcare Administrator",
  "Hospital Administrator",
  "Medical Director",
  "Chief Medical Officer",
  "CMO",
  "Pharmacist",
  "Clinical Pharmacist",
  "Pharmacy Manager",
  "Physical Therapist",
  "Occupational Therapist",
  "Speech Therapist",
  "Respiratory Therapist",
  "Radiologic Technologist",
  "Medical Laboratory Technician",
  "Lab Technician",
  "Medical Technologist",
  "Dental Hygienist",
  "Dentist",
  "Dental Assistant",
  "Optometrist",
  "Mental Health Counselor",
  "Psychologist",
  "Psychiatrist",
  "Social Worker",
  "Licensed Clinical Social Worker",
  "Healthcare Consultant",
  "Medical Billing Specialist",
  "Medical Coder",
  "Health Information Manager",
]

const educationRoles = [
  "Teacher",
  "Elementary School Teacher",
  "Middle School Teacher",
  "High School Teacher",
  "Special Education Teacher",
  "ESL Teacher",
  "Substitute Teacher",
  "Teaching Assistant",
  "Teacher's Aide",
  "Professor",
  "Assistant Professor",
  "Associate Professor",
  "Lecturer",
  "Adjunct Professor",
  "Academic Advisor",
  "School Counselor",
  "Guidance Counselor",
  "School Principal",
  "Vice Principal",
  "Assistant Principal",
  "School Administrator",
  "Superintendent",
  "Dean",
  "Academic Dean",
  "Department Chair",
  "Curriculum Developer",
  "Curriculum Specialist",
  "Instructional Designer",
  "Senior Instructional Designer",
  "E-Learning Developer",
  "Training Specialist",
  "Corporate Trainer",
  "Learning Experience Designer",
  "Education Consultant",
  "Tutor",
  "Education Coordinator",
  "Program Director",
  "Admissions Counselor",
  "Registrar",
  "Librarian",
]

const consultingRoles = [
  "Consultant",
  "Associate Consultant",
  "Senior Consultant",
  "Management Consultant",
  "Senior Management Consultant",
  "Strategy Consultant",
  "Senior Strategy Consultant",
  "Principal Consultant",
  "Director",
  "Managing Director",
  "Partner",
  "Senior Partner",
  "Associate Partner",
  "Business Consultant",
  "Senior Business Consultant",
  "IT Consultant",
  "Senior IT Consultant",
  "Technology Consultant",
  "Digital Consultant",
  "Digital Transformation Consultant",
  "Change Management Consultant",
  "Operations Consultant",
  "HR Consultant",
  "Financial Consultant",
  "Risk Consultant",
  "Healthcare Consultant",
  "Salesforce Consultant",
  "SAP Consultant",
  "ERP Consultant",
  "Data Consultant",
  "Analytics Consultant",
  "Process Improvement Consultant",
  "Supply Chain Consultant",
  "Real Estate Consultant",
  "Marketing Consultant",
  "Brand Consultant",
  "Sustainability Consultant",
  "ESG Consultant",
  "Implementation Consultant",
  "Solutions Consultant",
  "Engagement Manager",
  "Case Team Leader",
]

const mediaRoles = [
  "Journalist",
  "Senior Journalist",
  "Reporter",
  "Investigative Reporter",
  "News Editor",
  "Managing Editor",
  "Editor-in-Chief",
  "Editor",
  "Copy Editor",
  "Technical Writer",
  "Senior Technical Writer",
  "Grant Writer",
  "Blog Writer",
  "Scriptwriter",
  "Screenwriter",
  "Video Producer",
  "Senior Video Producer",
  "Executive Producer",
  "Film Producer",
  "Television Producer",
  "Podcast Producer",
  "Broadcast Producer",
  "News Anchor",
  "Broadcast Journalist",
  "Radio Host",
  "Media Buyer",
  "Media Planner",
  "Publicist",
  "Content Creator",
  "YouTube Creator",
  "Influencer",
  "Social Media Influencer",
  "Blogger",
  "Vlogger",
]

const realEstateRoles = [
  "Real Estate Agent",
  "Real Estate Broker",
  "Realtor",
  "Real Estate Associate",
  "Senior Real Estate Agent",
  "Managing Broker",
  "Property Manager",
  "Senior Property Manager",
  "Asset Manager",
  "Real Estate Analyst",
  "Commercial Real Estate Analyst",
  "Real Estate Developer",
  "Development Manager",
  "Leasing Agent",
  "Leasing Consultant",
  "Leasing Manager",
  "Real Estate Investor",
  "Real Estate Appraiser",
  "Mortgage Broker",
  "Loan Officer",
  "Title Officer",
  "Escrow Officer",
]

const constructionRoles = [
  "Construction Manager",
  "Project Manager",
  "Construction Superintendent",
  "Site Manager",
  "Site Supervisor",
  "General Contractor",
  "Construction Foreman",
  "Civil Engineer",
  "Senior Civil Engineer",
  "Structural Engineer",
  "Architect",
  "Senior Architect",
  "Project Architect",
  "Principal Architect",
  "Landscape Architect",
  "Urban Planner",
  "Estimator",
  "Cost Estimator",
  "Quantity Surveyor",
  "Construction Coordinator",
  "Safety Manager",
  "Safety Officer",
]

const hospitalityRoles = [
  "Hotel Manager",
  "General Manager",
  "Assistant General Manager",
  "Front Desk Agent",
  "Front Desk Manager",
  "Concierge",
  "Guest Services Manager",
  "Housekeeping Manager",
  "Executive Housekeeper",
  "Restaurant Manager",
  "Assistant Restaurant Manager",
  "Food and Beverage Manager",
  "F&B Director",
  "Chef",
  "Executive Chef",
  "Sous Chef",
  "Head Chef",
  "Pastry Chef",
  "Line Cook",
  "Prep Cook",
  "Server",
  "Bartender",
  "Bar Manager",
  "Sommelier",
  "Banquet Manager",
  "Catering Manager",
  "Event Manager",
  "Event Coordinator",
  "Event Planner",
  "Wedding Planner",
  "Meeting Planner",
  "Conference Manager",
  "Revenue Manager",
  "Reservations Manager",
]

const retailRoles = [
  "Retail Sales Associate",
  "Sales Associate",
  "Retail Associate",
  "Cashier",
  "Store Manager",
  "Assistant Store Manager",
  "Retail Manager",
  "District Manager",
  "Regional Manager",
  "Area Manager",
  "Retail Buyer",
  "Senior Buyer",
  "Merchandise Manager",
  "Merchandiser",
  "Visual Merchandiser",
  "Inventory Specialist",
  "Stock Associate",
  "Loss Prevention Manager",
  "Loss Prevention Specialist",
  "E-commerce Manager",
  "E-commerce Specialist",
  "Category Manager",
  "Brand Ambassador",
  "Department Manager",
  "Retail Operations Manager",
]

const executiveRoles = [
  "CEO",
  "Chief Executive Officer",
  "President",
  "Co-Founder",
  "Founder",
  "Managing Director",
  "General Manager",
  "Executive Director",
  "Board Member",
  "Board Director",
  "Chairman",
  "Vice Chairman",
]

const adminRoles = [
  "Executive Assistant",
  "Senior Executive Assistant",
  "Personal Assistant",
  "Administrative Assistant",
  "Office Manager",
  "Office Administrator",
  "Office Coordinator",
  "Administrative Coordinator",
  "Receptionist",
  "Front Desk Receptionist",
  "Virtual Assistant",
  "Data Entry Specialist",
  "File Clerk",
  "Administrative Specialist",
]

const skillsTradesRoles = [
  "Electrician",
  "Master Electrician",
  "Plumber",
  "Master Plumber",
  "HVAC Technician",
  "HVAC Installer",
  "Carpenter",
  "Cabinet Maker",
  "Welder",
  "Machinist",
  "CNC Operator",
  "Mechanic",
  "Auto Mechanic",
  "Diesel Mechanic",
  "Aircraft Mechanic",
  "Maintenance Technician",
  "Maintenance Manager",
  "Building Engineer",
  "Painter",
  "Roofer",
  "Mason",
  "Pipefitter",
  "Sheet Metal Worker",
]

const transportationRoles = [
  "Truck Driver",
  "Delivery Driver",
  "Bus Driver",
  "Pilot",
  "Commercial Pilot",
  "Captain",
  "Flight Attendant",
  "Air Traffic Controller",
  "Dispatcher",
  "Fleet Manager",
  "Transportation Manager",
  "Logistics Coordinator",
  "Shipping Coordinator",
  "Import/Export Specialist",
  "Customs Broker",
]

const scienceRoles = [
  "Research Scientist",
  "Senior Research Scientist",
  "Principal Scientist",
  "Staff Scientist",
  "Laboratory Manager",
  "Lab Technician",
  "Research Associate",
  "Research Assistant",
  "Chemist",
  "Senior Chemist",
  "Biochemist",
  "Biologist",
  "Microbiologist",
  "Geneticist",
  "Environmental Scientist",
  "Geologist",
  "Physicist",
  "Materials Scientist",
  "Statistician",
  "Biostatistician",
]

const engineeringRoles = [
  "Mechanical Engineer",
  "Senior Mechanical Engineer",
  "Electrical Engineer",
  "Senior Electrical Engineer",
  "Electronics Engineer",
  "Chemical Engineer",
  "Senior Chemical Engineer",
  "Process Engineer",
  "Manufacturing Engineer",
  "Industrial Engineer",
  "Quality Engineer",
  "Reliability Engineer",
  "Test Engineer",
  "Validation Engineer",
  "R&D Engineer",
  "Research Engineer",
  "Design Engineer",
  "CAD Designer",
  "CAD Engineer",
  "Aerospace Engineer",
  "Automotive Engineer",
  "Biomedical Engineer",
  "Environmental Engineer",
  "Nuclear Engineer",
  "Petroleum Engineer",
  "Mining Engineer",
  "Marine Engineer",
  "Controls Engineer",
  "Automation Engineer",
]

// Combine all roles
export const allJobRoles: string[] = [
  ...techRoles,
  ...productRoles,
  ...designRoles,
  ...salesRoles,
  ...marketingRoles,
  ...financeRoles,
  ...hrRoles,
  ...operationsRoles,
  ...customerServiceRoles,
  ...legalRoles,
  ...healthcareRoles,
  ...educationRoles,
  ...consultingRoles,
  ...mediaRoles,
  ...realEstateRoles,
  ...constructionRoles,
  ...hospitalityRoles,
  ...retailRoles,
  ...executiveRoles,
  ...adminRoles,
  ...skillsTradesRoles,
  ...transportationRoles,
  ...scienceRoles,
  ...engineeringRoles,
]

// Normalize role string for better matching
function normalizeRole(role: string): string {
  return role
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim()
}

// Calculate match score (higher = better match)
function calculateMatchScore(role: string, query: string): number {
  const normalizedRole = normalizeRole(role)
  const normalizedQuery = normalizeRole(query)
  
  // Exact match
  if (normalizedRole === normalizedQuery) return 1000
  
  // Starts with query (highest priority for partial)
  if (normalizedRole.startsWith(normalizedQuery)) return 500 + (normalizedQuery.length / normalizedRole.length) * 100
  
  // Role contains the full query
  if (normalizedRole.includes(normalizedQuery)) return 300 + (normalizedQuery.length / normalizedRole.length) * 100
  
  // All query words found in role
  const queryWords = normalizedQuery.split(' ').filter(w => w.length > 1)
  const roleWords = normalizedRole.split(' ')
  const allWordsFound = queryWords.every(qw => 
    roleWords.some(rw => rw.startsWith(qw) || rw.includes(qw))
  )
  if (allWordsFound && queryWords.length > 0) {
    return 200 + (queryWords.length * 20)
  }
  
  // Partial word matches (fuzzy)
  let partialScore = 0
  for (const qw of queryWords) {
    for (const rw of roleWords) {
      if (rw.startsWith(qw)) {
        partialScore += 50
      } else if (rw.includes(qw)) {
        partialScore += 25
      }
    }
  }
  if (partialScore > 0) return partialScore
  
  return 0
}

// Smart search function
export function searchRoles(query: string, limit: number = 10): string[] {
  if (!query || query.trim().length < 2) return []
  
  const normalizedQuery = normalizeRole(query)
  
  // Score all roles
  const scoredRoles = allJobRoles
    .map(role => ({
      role,
      score: calculateMatchScore(role, normalizedQuery)
    }))
    .filter(item => item.score > 0)
    .sort((a, b) => b.score - a.score)
  
  // Return top results
  return scoredRoles.slice(0, limit).map(item => item.role)
}

// Export for backward compatibility
export const commonRoles = allJobRoles

// Role-specific question banks
export const roleSpecificQuestions: Record<string, string[]> = {
  frontend: [
    "How would you optimize the performance of a React application?",
    "Explain your approach to responsive design and mobile-first development",
    "How do you handle state management in large-scale applications?",
    "Describe your experience with component libraries and design systems",
    "How would you implement infinite scrolling or virtualization?",
    "Explain your approach to accessibility (a11y) in web applications",
    "How do you optimize bundle size and loading performance?",
    "Describe your testing strategy for frontend applications",
    "How would you implement server-side rendering (SSR)?",
    "Explain your approach to CSS-in-JS vs traditional CSS",
  ],
  backend: [
    "How would you design a scalable API architecture?",
    "Explain your approach to database optimization and indexing",
    "How do you handle authentication and authorization at scale?",
    "Describe your experience with microservices vs monolith architecture",
    "How would you implement caching strategies for APIs?",
    "Explain your approach to API versioning and backward compatibility",
    "How do you handle rate limiting and API throttling?",
    "Describe your experience with message queues and event-driven architecture",
    "How would you design a background job processing system?",
    "Explain your approach to monitoring and logging in production",
  ],
  fullstack: [
    "How do you balance frontend and backend responsibilities in your work?",
    "Describe a full-stack feature you built from scratch",
    "How do you handle real-time data synchronization between client and server?",
    "Explain your approach to API design for frontend consumption",
    "How would you architect a new web application from the ground up?",
    "Describe your experience with modern deployment and DevOps practices",
    "How do you optimize the entire stack for performance?",
    "Explain your testing strategy across the full stack",
  ],
  mobile: [
    "How do you handle offline functionality in mobile apps?",
    "Explain your approach to mobile app performance optimization",
    "How do you manage different screen sizes and device capabilities?",
    "Describe your experience with native vs cross-platform development",
    "How would you implement push notifications at scale?",
    "Explain your approach to mobile app security",
    "How do you handle app store submissions and updates?",
    "Describe your mobile testing and QA strategy",
  ],
  data: [
    "How would you design a data pipeline for real-time analytics?",
    "Explain your approach to data modeling and schema design",
    "How do you handle data quality and validation?",
    "Describe your experience with distributed data processing",
    "How would you optimize slow-running queries?",
    "Explain your approach to data warehousing vs data lakes",
    "How do you ensure data privacy and compliance (GDPR, etc.)?",
    "Describe your experience with ETL/ELT processes",
  ],
  ml: [
    "How would you deploy a machine learning model to production?",
    "Explain your approach to feature engineering",
    "How do you handle model versioning and monitoring?",
    "Describe your experience with model evaluation and metrics",
    "How would you address model bias and fairness?",
    "Explain your approach to hyperparameter tuning",
    "How do you handle model retraining and continuous learning?",
    "Describe your experience with MLOps and infrastructure",
  ],
  devops: [
    "How would you design a CI/CD pipeline from scratch?",
    "Explain your approach to infrastructure as code (IaC)",
    "How do you handle incident response and on-call rotations?",
    "Describe your experience with container orchestration",
    "How would you implement zero-downtime deployments?",
    "Explain your approach to monitoring and observability",
    "How do you handle infrastructure scaling and cost optimization?",
    "Describe your experience with disaster recovery and backup strategies",
  ],
  security: [
    "How would you conduct a security audit for a web application?",
    "Explain your approach to threat modeling",
    "How do you handle vulnerability management and patching?",
    "Describe your experience with security compliance (SOC2, ISO, etc.)",
    "How would you implement secure authentication and authorization?",
    "Explain your approach to secrets management",
    "How do you handle security incident response?",
    "Describe your experience with penetration testing",
  ],
  leadership: [
    "How do you prioritize technical roadmap items?",
    "Explain your approach to hiring and building teams",
    "How do you handle conflicts within your team?",
    "Describe your experience with agile methodologies",
    "How do you balance technical debt with feature development?",
    "Explain your approach to performance reviews and career development",
    "How do you ensure knowledge sharing within the team?",
    "Describe a time you had to make a difficult technical decision",
  ],
  product: [
    "How do you prioritize features in your product roadmap?",
    "Explain your approach to gathering and analyzing user feedback",
    "How do you measure product success and define KPIs?",
    "Describe a product you launched and its impact",
    "How do you work with engineering and design teams?",
    "Explain your approach to product discovery and validation",
    "How do you handle competing stakeholder priorities?",
    "Describe how you've used data to make product decisions",
  ],
  design: [
    "Walk me through your design process from research to delivery",
    "How do you balance user needs with business requirements?",
    "Describe how you handle design feedback and iteration",
    "How do you ensure consistency across a product's design?",
    "Explain your approach to user research and testing",
    "How do you advocate for good design decisions?",
    "Describe a challenging design problem you solved",
    "How do you stay current with design trends and best practices?",
  ],
  sales: [
    "How do you approach cold outreach and prospecting?",
    "Describe your sales process from lead to close",
    "How do you handle objections during the sales cycle?",
    "Tell me about your most successful deal and how you closed it",
    "How do you manage and prioritize your sales pipeline?",
    "Describe your approach to building long-term client relationships",
    "How do you stay motivated during slow periods?",
    "What's your strategy for upselling and cross-selling?",
  ],
  marketing: [
    "How do you measure the success of marketing campaigns?",
    "Describe your approach to content strategy and creation",
    "How do you identify and reach your target audience?",
    "Tell me about a campaign that didn't perform well and what you learned",
    "How do you balance brand awareness with lead generation?",
    "Describe your experience with marketing analytics and attribution",
    "How do you stay updated on marketing trends and best practices?",
    "What's your approach to A/B testing and optimization?",
  ],
  finance: [
    "How do you approach financial forecasting and budgeting?",
    "Describe your experience with financial modeling",
    "How do you handle month-end and year-end close processes?",
    "Tell me about a time you identified cost-saving opportunities",
    "How do you ensure compliance with financial regulations?",
    "Describe your approach to variance analysis",
    "How do you communicate financial insights to non-finance stakeholders?",
    "What's your experience with financial reporting systems?",
  ],
  hr: [
    "How do you approach talent acquisition and recruitment?",
    "Describe your experience with employee relations and conflict resolution",
    "How do you handle sensitive HR situations?",
    "Tell me about a successful employee retention initiative you implemented",
    "How do you ensure compliance with employment laws?",
    "Describe your approach to performance management",
    "How do you build and maintain company culture?",
    "What's your strategy for diversity and inclusion?",
  ],
  operations: [
    "How do you identify and eliminate operational inefficiencies?",
    "Describe your approach to process improvement",
    "How do you manage cross-functional projects?",
    "Tell me about a time you improved operational metrics",
    "How do you balance quality with speed and cost?",
    "Describe your experience with supply chain management",
    "How do you handle capacity planning and resource allocation?",
    "What's your approach to vendor management?",
  ],
  customerservice: [
    "How do you handle difficult or upset customers?",
    "Describe your approach to measuring customer satisfaction",
    "How do you prioritize customer issues and requests?",
    "Tell me about a time you turned a negative customer experience into a positive one",
    "How do you balance customer needs with company policies?",
    "Describe your experience with customer service tools and systems",
    "How do you train and develop customer service team members?",
    "What's your strategy for reducing customer churn?",
  ],
  healthcare: [
    "How do you ensure patient safety and quality of care?",
    "Describe your approach to handling medical emergencies",
    "How do you manage your time with multiple patients?",
    "Tell me about a challenging patient interaction and how you handled it",
    "How do you stay current with medical best practices?",
    "Describe your experience with electronic health records",
    "How do you communicate complex medical information to patients?",
    "What's your approach to working in a multidisciplinary healthcare team?",
  ],
  education: [
    "How do you engage students with different learning styles?",
    "Describe your classroom management approach",
    "How do you assess student progress and learning outcomes?",
    "Tell me about a lesson plan that was particularly effective",
    "How do you handle difficult students or parents?",
    "Describe your approach to curriculum development",
    "How do you integrate technology into your teaching?",
    "What's your strategy for differentiated instruction?",
  ],
  legal: [
    "How do you approach legal research and case preparation?",
    "Describe your experience with contract negotiation and drafting",
    "How do you manage multiple cases or projects simultaneously?",
    "Tell me about a complex legal issue you resolved",
    "How do you communicate legal concepts to non-legal stakeholders?",
    "Describe your approach to risk management and compliance",
    "How do you stay current with changes in law and regulations?",
    "What's your experience with dispute resolution and litigation?",
  ],
  consulting: [
    "How do you approach problem-solving for client engagements?",
    "Describe your experience with stakeholder management",
    "How do you handle ambiguous or complex client problems?",
    "Tell me about a successful project you delivered and its impact",
    "How do you build credibility and trust with clients?",
    "Describe your approach to data analysis and insights",
    "How do you manage competing client priorities?",
    "What's your experience with change management?",
  ],
  creative: [
    "Walk me through your creative process from concept to execution",
    "How do you handle creative feedback and revisions?",
    "Describe a project where you had to balance creativity with client constraints",
    "Tell me about a time your creative work exceeded expectations",
    "How do you stay inspired and overcome creative blocks?",
    "Describe your experience collaborating with other creatives",
    "How do you manage multiple creative projects with tight deadlines?",
    "What's your approach to presenting and defending your creative work?",
  ],
  hospitality: [
    "How do you ensure exceptional guest experiences?",
    "Describe your approach to handling guest complaints",
    "How do you manage staff during peak periods?",
    "Tell me about a time you exceeded guest expectations",
    "How do you balance service quality with operational efficiency?",
    "Describe your experience with revenue management",
    "How do you train and develop hospitality staff?",
    "What's your approach to maintaining standards and consistency?",
  ],
  retail: [
    "How do you drive sales and meet revenue targets?",
    "Describe your approach to visual merchandising and store layout",
    "How do you handle inventory management and shrinkage?",
    "Tell me about a successful promotion or event you executed",
    "How do you coach and develop retail staff?",
    "Describe your experience with retail analytics and reporting",
    "How do you create a positive customer shopping experience?",
    "What's your strategy for managing seasonal fluctuations?",
  ],
  general: [
    "Tell me about yourself and your career journey",
    "What are your greatest strengths and how do they help you succeed?",
    "Describe a challenging situation you faced and how you overcame it",
    "How do you prioritize tasks when you have multiple deadlines?",
    "Tell me about a time you worked effectively in a team",
    "What motivates you in your professional life?",
    "Describe a time you had to learn something new quickly",
    "How do you handle feedback and criticism?",
  ],
}

// Detect role category from description
export function detectRoleCategory(role: string): string {
  const roleLower = role.toLowerCase()
  
  // Tech roles (check more specific first)
  if (roleLower.includes('frontend') || roleLower.includes('front-end') || roleLower.includes('react') || roleLower.includes('vue') || roleLower.includes('angular') || roleLower.includes('ui developer') || roleLower.includes('ui engineer')) {
    return 'frontend'
  }
  if (roleLower.includes('backend') || roleLower.includes('back-end') || roleLower.includes('node.js') || roleLower.includes('python developer') || roleLower.includes('python engineer') || roleLower.includes('java developer') || roleLower.includes('java engineer') || roleLower.includes('go developer') || roleLower.includes('golang') || roleLower.includes('.net') || roleLower.includes('ruby') || roleLower.includes('php') || roleLower.includes('api developer') || roleLower.includes('api engineer')) {
    return 'backend'
  }
  if (roleLower.includes('full stack') || roleLower.includes('fullstack') || roleLower.includes('full-stack')) {
    return 'fullstack'
  }
  if (roleLower.includes('mobile') || roleLower.includes('ios') || roleLower.includes('android') || roleLower.includes('react native') || roleLower.includes('flutter') || roleLower.includes('swift developer') || roleLower.includes('kotlin developer')) {
    return 'mobile'
  }
  if (roleLower.includes('data engineer') || roleLower.includes('data analyst') || roleLower.includes('analytics engineer') || roleLower.includes('bi developer') || roleLower.includes('database') || roleLower.includes('etl') || roleLower.includes('data warehouse')) {
    return 'data'
  }
  if (roleLower.includes('machine learning') || roleLower.includes('ml engineer') || roleLower.includes('ai engineer') || roleLower.includes('data scientist') || roleLower.includes('research scientist') || roleLower.includes('deep learning') || roleLower.includes('nlp') || roleLower.includes('computer vision') || roleLower.includes('mlops')) {
    return 'ml'
  }
  if (roleLower.includes('devops') || roleLower.includes('sre') || roleLower.includes('site reliability') || roleLower.includes('cloud engineer') || roleLower.includes('infrastructure') || roleLower.includes('platform engineer') || roleLower.includes('kubernetes') || roleLower.includes('aws') || roleLower.includes('azure') || roleLower.includes('gcp')) {
    return 'devops'
  }
  if (roleLower.includes('security') || roleLower.includes('cybersecurity') || roleLower.includes('penetration') || roleLower.includes('cryptography')) {
    return 'security'
  }
  if (roleLower.includes('software engineer') || roleLower.includes('software developer') || roleLower.includes('programmer')) {
    return 'backend' // Default tech roles to backend
  }
  
  // Product roles
  if (roleLower.includes('product manager') || roleLower.includes('product owner') || roleLower.includes('program manager') || roleLower.includes('project manager') || roleLower.includes('scrum master') || roleLower.includes('agile coach') || roleLower.includes('delivery manager')) {
    return 'product'
  }
  
  // Design roles
  if (roleLower.includes('designer') || roleLower.includes('ux') || roleLower.includes('ui') || roleLower.includes('creative director') || roleLower.includes('art director') || roleLower.includes('illustrator') || roleLower.includes('photographer')) {
    return 'design'
  }
  
  // Leadership (check after specific roles)
  if (roleLower.includes('cto') || roleLower.includes('chief technology') || roleLower.includes('vp of engineering') || roleLower.includes('director of engineering') || roleLower.includes('engineering manager') || roleLower.includes('tech lead') || roleLower.includes('head of engineering')) {
    return 'leadership'
  }
  
  // Non-Tech roles
  if (roleLower.includes('sales') || roleLower.includes('account executive') || roleLower.includes('business development') || roleLower.includes('bdr') || roleLower.includes('sdr') || roleLower.includes('account manager') || roleLower.includes('customer success')) {
    return 'sales'
  }
  if (roleLower.includes('marketing') || roleLower.includes('growth') || roleLower.includes('seo') || roleLower.includes('content') || roleLower.includes('brand') || roleLower.includes('copywriter') || roleLower.includes('social media') || roleLower.includes('pr ') || roleLower.includes('public relations') || roleLower.includes('communications')) {
    return 'marketing'
  }
  if (roleLower.includes('finance') || roleLower.includes('accounting') || roleLower.includes('accountant') || roleLower.includes('financial') || roleLower.includes('controller') || roleLower.includes('treasurer') || roleLower.includes('cfo') || roleLower.includes('auditor') || roleLower.includes('tax') || roleLower.includes('bookkeeper')) {
    return 'finance'
  }
  if (roleLower.includes('hr ') || roleLower.includes('human resource') || roleLower.includes('recruiter') || roleLower.includes('talent') || roleLower.includes('people operations') || roleLower.includes('chro') || roleLower.includes('chief people')) {
    return 'hr'
  }
  if (roleLower.includes('operations') || roleLower.includes('supply chain') || roleLower.includes('logistics') || roleLower.includes('procurement') || roleLower.includes('warehouse') || roleLower.includes('coo') || roleLower.includes('chief operating') || roleLower.includes('inventory') || roleLower.includes('fulfillment')) {
    return 'operations'
  }
  if (roleLower.includes('customer service') || roleLower.includes('customer support') || roleLower.includes('support specialist') || roleLower.includes('help desk') || roleLower.includes('call center') || roleLower.includes('client services')) {
    return 'customerservice'
  }
  if (roleLower.includes('nurse') || roleLower.includes('doctor') || roleLower.includes('physician') || roleLower.includes('medical') || roleLower.includes('healthcare') || roleLower.includes('clinical') || roleLower.includes('pharmacist') || roleLower.includes('therapist') || roleLower.includes('dentist') || roleLower.includes('surgeon')) {
    return 'healthcare'
  }
  if (roleLower.includes('teacher') || roleLower.includes('professor') || roleLower.includes('instructor') || roleLower.includes('education') || roleLower.includes('academic') || roleLower.includes('trainer') || roleLower.includes('principal') || roleLower.includes('dean') || roleLower.includes('librarian')) {
    return 'education'
  }
  if (roleLower.includes('attorney') || roleLower.includes('lawyer') || roleLower.includes('legal') || roleLower.includes('counsel') || roleLower.includes('paralegal') || roleLower.includes('compliance')) {
    return 'legal'
  }
  if (roleLower.includes('consultant') || roleLower.includes('advisory') || roleLower.includes('consulting')) {
    return 'consulting'
  }
  if (roleLower.includes('hotel') || roleLower.includes('restaurant') || roleLower.includes('hospitality') || roleLower.includes('chef') || roleLower.includes('catering') || roleLower.includes('concierge') || roleLower.includes('bartender') || roleLower.includes('event manager') || roleLower.includes('event planner')) {
    return 'hospitality'
  }
  if (roleLower.includes('retail') || roleLower.includes('store manager') || roleLower.includes('merchandise') || roleLower.includes('sales associate') || roleLower.includes('cashier') || roleLower.includes('buyer')) {
    return 'retail'
  }
  if (roleLower.includes('journalist') || roleLower.includes('editor') || roleLower.includes('writer') || roleLower.includes('reporter') || roleLower.includes('producer') || roleLower.includes('content creator') || roleLower.includes('influencer')) {
    return 'creative'
  }
  
  // Executive roles
  if (roleLower.includes('ceo') || roleLower.includes('chief executive') || roleLower.includes('president') || roleLower.includes('founder') || roleLower.includes('managing director') || roleLower.includes('general manager') || roleLower.includes('executive director')) {
    return 'leadership'
  }
  
  // Manager roles (catch-all for remaining managers)
  if (roleLower.includes('manager') || roleLower.includes('director') || roleLower.includes('vp') || roleLower.includes('vice president') || roleLower.includes('head of') || roleLower.includes('lead')) {
    return 'leadership'
  }
  
  // Default to general behavioral questions
  return 'general'
}
